_target_: sde_sampler.models.egnn.EGNN_dynamics
#_partial_: true
n_particles: 13
n_dimension: 3
hidden_nf: 128
n_layers: 5
act_fn:
  _target_: torch.nn.SiLU
recurrent: True
tanh: True
attention: True
condition_time: True
agg: "sum"