# @package _global_
defaults:
  - oc_base
  - /prior: gauss_truncate
  - /sde: 
  - /model@generative_ctrl: score
  - /loss: exponential_sde_lv
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.DDS

train_timesteps:
  rescale_t: "cosine"
  steps: 
  end: 12.8
  dt: 0.05

prior:
  scale: ${loss.sigma}

# Model
generative_ctrl:
  clip_score: 10.
  clip_model: 10.
