# @package _global_
defaults:
  - oc_base
  - /prior: gauss_truncate
  - /sde: vp_dw4
  - /model@generative_ctrl: score_egnn_dw4
  - /loss: reference_sde
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.EulerDDS

# Model
generative_ctrl:
  clip_score: 1000.
  clip_model: 10.
