# @package _global_
defaults:
  - oc_base
  - /prior: gauss_truncate
  - /sde: vp_10
  - /model@generative_ctrl: lerp
  - /loss: time_reversal_lv
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.Bridge

# Model
generative_ctrl:
  clip_score: 10.
  clip_model: 10.
