_target_: sde_sampler.distr.lj_particles.LennardJonesPotential
dim: 39
n_particles: 13
data_path: "data/particle_exp/train_split_LJ13-1000.npy"
#data_path_train: "data/train_split_LJ13-1000.npy"
#data_path_val: "data/val_split_LJ13-1000.npy"
#data_path_test: "data/test_split_LJ13-1000.npy"
#data_normalization_factor: 1.0
#is_molecule: True

#device: ${trainer.accelerator}